export enum WebSocketDataType {
  OperationNotAllowedAtCurrentState = "OperationNotAllowedAtCurrentState",
  PlayerJoined = "PlayerJoined",
  PlayerLeft = "PlayerLeft",
  PeekingPhaseStarted = "PeekingPhaseStarted",
  PlayerTurn = "PlayerTurn",
  CardWasDrawn = "CardWasDrawn",
  PlayerWentCrabul = "PlayerWentCrabul",
  DrawnCard = "DrawnCard",
  CardSwapped = "CardSwapped",
  CardDiscarded = "CardDiscarded",
  PowerActivated = "PowerActivated",
  PowerUsed = "PowerUsed",
  PeekedCard = "PeekedCard",
  GameTerminated = "GameTerminated",
  SameCardAttempt = "SameCardAttempt",
  CardReplaced = "CardReplaced",
}